In [2]:
import plotly
import plotly.graph_objects as go
import numpy as np
import pydyns as ds
import copy

In [1]:
import pydyns as dyns
# Lorenz system
dynamic_system = dyns.DynamicSystem([0.1,0.1,0.1], ["10*(y-x)","x*(28-z)-y","x*y-2.66*z"], 'x,y,z')
dynamic_system.SetDt(0.01)
trajectory = dynamic_system.GetTrajectory(100)
trajectory

[array([0.1, 0.1, 0.1], dtype=float64),
 array([0.1013001 , 0.12688855, 0.09748759], dtype=float64),
 array([0.10505119, 0.1542185 , 0.09507153], dtype=float64),
 array([0.11109399, 0.18264202, 0.09275539], dtype=float64),
 array([0.11934435, 0.21277139, 0.09054518], dtype=float64),
 array([0.12978325, 0.24519885, 0.08844964], dtype=float64),
 array([0.1424496 , 0.28051374, 0.08648067], dtype=float64),
 array([0.15743517, 0.31931785, 0.08465404], dtype=float64),
 array([0.17488141, 0.3622395 , 0.08299027], dtype=float64),
 array([0.19497797, 0.40994679, 0.08151592], dtype=float64),
 array([0.21796243, 0.46316044, 0.08026504], dtype=float64),
 array([0.24412144, 0.52266673, 0.0792812 ], dtype=float64),
 array([0.2737929 , 0.58933058, 0.07861999], dtype=float64),
 array([0.3073692 , 0.66410934, 0.07835221], dtype=float64),
 array([0.34530155, 0.74806738, 0.07856789], dtype=float64),
 array([0.38810535, 0.84239179, 0.07938137], dtype=float64),
 array([0.4363665 , 0.94840945, 0.08093783], 

In [3]:
d_closed_system = ds.DynamicSystem([1,2,3], ["x2","x3","1/4*10^3*(0-220*10^(-3)*x3-1000*10^(-3)*x2-x1)"], 'x1,x2,x3')
d_closed_system.SetDt(0.001)
trajectory_closed = np.array(d_closed_system.GetTrajectory(5))
Xs_closed = trajectory_closed.transpose().astype('float')

In [3]:
d_closed_system_2 = ds.DynamicSystem([0,0,0], ["x2","x3","1/35*10^4*(sin(10*t)-4200*10^(-4)*x3-80000*10^(-4)*x2-x1)"], 'x1,x2,x3')
d_closed_system_2.SetDt(0.001)
trajectory_closed_2 = np.array(d_closed_system_2.GetTrajectory(4))
Xs_closed_2 = trajectory_closed_2.transpose().astype('float')

In [4]:
d_system = ds.DynamicSystem([0,0,0], ["x2","x3","1/4*10^3*(1-220*10^(-3)*x3-1000*10^(-3)*x2)"], 'x1,x2,x3')
d_system.SetDt(0.001)
trajectory = np.array(d_system.GetTrajectory(5))
Xs = trajectory.transpose().astype('float')

In [5]:
fig = go.Figure()
Ts = np.linspace(0, 4, len(trajectory_closed_2))
# fig.add_trace(
#     go.Scatter(
#         x=Ts, y=Xs[0], name="X1 разомкнутой", line_shape='spline', line=dict(color='rgba(255, 50, 100, 0.3)', width = 4)
#         )
#     )
# fig.add_trace(
#     go.Scatter(
#         x=Ts, y=Xs[1], name="X2 разомкнутой", line_shape='spline', line=dict(color='rgba(50, 255, 100, 0.3)', width = 4)
#         )
#     )
# fig.add_trace(
#     go.Scatter(
#         x=Ts, y=Xs[2], name="X3 разомкнутой", line_shape='spline', line=dict(color='rgba(100, 50, 255, 0.3)', width = 4)
#         )
#     )

# fig.add_trace(
#     go.Scatter(
#         x=Ts, y=Xs_closed[0], name="X1 нул. воздействие", line_shape='spline', line=dict(color='rgba(255, 50, 100, 1)', width = 4)
#         # mode='lines+markers',
#         )
#     )
# fig.add_trace(
#     go.Scatter(
#         x=Ts, y=Xs_closed[1], name="X2 нул. воздействие", line_shape='spline', line=dict(color='rgba(50, 255, 100, 1)', width = 4)
#         )
#     )
# fig.add_trace(
#     go.Scatter(
#         x=Ts, y=Xs_closed[2], name="X3 нул. воздействие", line_shape='spline', line=dict(color='rgba(100, 50, 255, 1)', width = 4)
#         )
#     )

fig.add_trace(
    go.Scatter(
        x=Ts, y=Xs_closed_2[0] + Xs_closed_2[1], name="Y", line_shape='spline'#, line=dict(color='rgba(255, 50, 100, 0.3)', width = 4)
        # mode='lines+markers',
        )
    )

# fig.add_trace(
#     go.Scatter(
#         x=Ts, y=Xs_closed_2[0], name="X1 ед. воздействие", line_shape='spline'#, line=dict(color='rgba(255, 50, 100, 0.3)', width = 4)
#         # mode='lines+markers',
#         )
#     )
# fig.add_trace(
#     go.Scatter(
#         x=Ts, y=Xs_closed_2[1], name="X2 ед. воздействие", line_shape='spline'#, line=dict(color='rgba(50, 255, 100, 0.3)', width = 4)
#         )
#     )
# fig.add_trace(
#     go.Scatter(
#         x=Ts, y=Xs_closed_2[2], name="X3 ед. воздействие", line_shape='spline'#, line=dict(color='rgba(100, 50, 255, 0.3)', width = 4)
#         )
#     )

fig.add_trace(
    go.Scatter(
        x=Ts, y=0.809*np.sin(10*Ts - 0.63), name="Теоретический Y", line_shape='spline'#, line=dict(color='rgba(0, 0, 0, 0.3)', width = 2)
        )
    )

fig.update_layout(
    # title='ЛАЧХ',  
    autosize=False,
    width=1000, height=500,
    margin=dict(l=50, r=50, b=50, t=50),
    template='simple_white',
    xaxis_title=r't',
    # yaxis_title=r'$d, r \text{ (solar radius)}$'
    )

fig.update_yaxes(tick0=0, dtick=0)

fig.update_xaxes(showgrid=True)
fig.update_yaxes(showgrid=True)

fig.show()
plotly.io.write_image(fig, 'Сравнение переходного процесса при нулевом входе и еденичном входе условиях.pdf', format='pdf')

ValueError: 
Image export using the "kaleido" engine requires the kaleido package,
which can be installed using pip:
    $ pip install -U kaleido


In [146]:
i = complex(0, 1)
s = lambda w: i * w

In [149]:
ws = lambda w: 7*(s(w)+1)/(s(w)*(0.01*s(w)+1)*(0.5*s(w)+1) + 7*(s(w)+1))
#ws = lambda w: 10 / s(w) / (0.1*s(w)+1) / (0.08*s(w)+1)

In [159]:
W = np.linspace(-1, 3, 1001)
WS = 20 * np.log10(np.abs(ws(np.power(10,W))))
print(20 * np.log10(np.abs(ws(np.power(10, 1.588)))))
fig = go.Figure()
fig.add_trace(
    go.Scatter(
        x=W, y=WS, name="Lm", line_shape='spline',
        # mode='lines+markers',
        line=dict(color='black')
        )
    )

fig.update_layout(
    # title='ЛАЧХ',  
    autosize=False,
    width=500, height=500,
    margin=dict(l=50, r=50, b=50, t=50),
    template='simple_white',
    xaxis_title=r'lg(ω)',
    # yaxis_title=r'$d, r \text{ (solar radius)}$'
    )

fig.update_yaxes(tick0=0, dtick=20)

fig.update_xaxes(showgrid=True)
fig.update_yaxes(showgrid=True)

fig.update_yaxes(range=[-160, 25])
fig.update_xaxes(range=[-1.5, 3.5])

fig.add_annotation(
    x=3.5, y=-160,
    text="",
    ax=-150, ay=0,
    xshift=2,
    yshift=0,
    showarrow=True,
    arrowsize=20,
    arrowwidth=0.1,
    arrowhead=1
    )

fig.add_annotation(
    x=-1.5, y=25,
    text="",
    ax=0, ay=150,
    xshift=0,
    yshift=2,
    showarrow=True,
    arrowsize=20,
    arrowwidth=0.1,
    arrowhead=1
    )

fig.show(), plotly.io.write_image(fig, 'Численная ЛАЧХ для замкнутой системы.pdf', format='pdf')

-8.929538407575162


(None, None)

In [151]:
W = np.linspace(-1, 3, 1001)
WS = 20 * np.log10(np.abs(ws(np.power(10,W))))
fig = go.Figure()

# X1 = np.linspace(W[1], np.log10(10), 2)
# Y1 = -20*X1 + 20
# fig.add_trace(
#     go.Scatter(
#         x=X1, y=Y1, line_shape='spline',
#         mode='lines',
#         line=dict(color='gray')
#         )
# )

# X2 = np.linspace(np.log10(10), np.log10(12.5), 2)
# Y2 = -20*X2 -20*(X2-np.log10(10)) + 20
# print(Y2)
# fig.add_trace(
#     go.Scatter(
#         x=X2, y=Y2, line_shape='spline',
#         mode='lines+markers',
#         line=dict(color='gray')
#         )
# )

# X3 = np.linspace(np.log10(12.5), W[len(W) - 1], 2)
# Y3 = -20*X3 -20*(X3-np.log10(10)) - 20*(X3 - np.log10(12.5)) + 20
# fig.add_trace(
#     go.Scatter(
#         x=X3, y=Y3, line_shape='spline',
#         mode='lines',
#         line=dict(color='gray')
#         )
# )

fig.add_trace(
    go.Scatter(
        x=W, y=WS, name="Lm", line_shape='spline',
        # mode='lines+markers',
        line=dict(color='black')
        )
    )

fig.update_layout(
    # title='ЛАЧХ',  
    autosize=False,
    width=500, height=500,
    margin=dict(l=50, r=50, b=50, t=50),
    template='simple_white',
    xaxis_title=r'lg(ω)',
    # yaxis_title=r'$d, r \text{ (solar radius)}$'
    )

fig.update_yaxes(tick0=0, dtick=20)

fig.update_xaxes(showgrid=True)
fig.update_yaxes(showgrid=True)

fig.update_yaxes(range=[-140, 50])
fig.update_xaxes(range=[-1.5, 3.5])

fig.add_annotation(
    x=3.5, y=-140,
    text="",
    ax=-150, ay=0,
    xshift=2,
    yshift=0,
    showarrow=True,
    arrowsize=20,
    arrowwidth=0.1,
    arrowhead=1
    )

fig.add_annotation(
    x=-1.5, y=50,
    text="",
    ax=0, ay=150,
    xshift=0,
    yshift=2,
    showarrow=True,
    arrowsize=20,
    arrowwidth=0.1,
    arrowhead=1
    )

# fig.add_annotation(x=-0.3, y=12,
#             text="-20 Дб/дек",
#             showarrow=False)

# fig.add_annotation(x=1.6, y=-65,
#             text="-60 Дб/дек",
#             showarrow=False)

# fig.add_annotation(x=1.5, y=3,
#             text="-40 Дб/дек",
#             showarrow=False)

fig.update_layout(showlegend=False)
fig.show(), plotly.io.write_image(fig, 'Сравнение ЛАЧХ.pdf', format='pdf')

(None, None)

In [71]:
W = np.linspace(-100, 1000, 1001)
WS = ws(W)
argWS = np.arctan2(WS.imag, WS.real) * 180 / np.pi
argWS[argWS > 0] -= 360

fig = go.Figure()
fig.add_trace(
    go.Scatter(
        x=np.log10(W), y=argWS, name="Lm", line_shape='spline',
        # mode='lines+markers',
        line=dict(color='black')
        )
    )

fig.update_layout(
    # title='ЛАЧХ',  
    autosize=False,
    width=500, height=500,
    margin=dict(l=50, r=50, b=50, t=50),
    template='simple_white',
    xaxis_title=r'lg(ω)',
    # yaxis_title=r'$d, r \text{ (solar radius)}$'
    )

fig.update_yaxes(tick0=0, dtick=90)

fig.update_xaxes(zeroline=True)
fig.update_yaxes(zeroline=True)

fig.update_xaxes(showgrid=True)
fig.update_yaxes(showgrid=True)

fig.update_yaxes(range=[-270-45, 0+45])
fig.update_xaxes(range=[-1.5, 3.5])

fig.add_annotation(
    x=3.5, y=-270-45,
    text="",
    ax=-150, ay=0,
    xshift=2,
    yshift=0,
    showarrow=True,
    arrowsize=20,
    arrowwidth=0.1,
    arrowhead=1
    )

fig.add_annotation(
    x=-1.5, y=0+45,
    text="",
    ax=0, ay=150,
    xshift=0,
    yshift=2,
    showarrow=True,
    arrowsize=20,
    arrowwidth=0.1,
    arrowhead=1
    )

fig.show()

C:\Users\stas2\AppData\Local\Temp\ipykernel_21572\3955523910.py:9: RuntimeWarning:

invalid value encountered in log10



In [125]:
W_lg = np.linspace(-2.5, 4, 1001)
WS = ws(np.power(10,W_lg))
argWS = np.arctan2(WS.imag, WS.real) * 180 / np.pi
argWS[argWS > 0] -= 360

print(np.arctan2(ws(np.power(10,1)).imag, ws(np.power(10,1)).real) * 180 / np.pi)

W_lin = np.linspace(W_lg[0], W_lg[len(W_lg)-1], 1000)

fig = go.Figure()

# fig.add_trace(
#     go.Scatter(
#         x=W_lin, y=-90*np.ones(len(W_lin)), name="Lm", line_shape='spline',
#         line=dict(color='rgba(0, 0, 0, 0.3)', width = 2)
#         )
#     )

def AperiodicFunction(x, T):
    if x < np.log10(1/T/10):
        return 0
    elif x <= np.log10(1/T/10) + 2:
        return -45*(x-np.log10(1/T/10))
    else:
        return -90
    
def DerevativeFunction(x, T):
    if x < np.log10(1/T/10):
        return 0
    elif x <= np.log10(1/T/10) + 2:
        return 45*(x-np.log10(1/T/10))
    else:
        return 90

# fig.add_trace(
#     go.Scatter(
#         x=W_lin, y=list(map(AperiodicFunction, W_lin, 0.5*np.ones(len(W_lin)))), name="Lm", line_shape='spline',
#         line=dict(color='rgba(0, 0, 0, 0.3)', width = 2)
#         )
#     )

# fig.add_trace(
#     go.Scatter(
#         x=W_lin, y=list(map(AperiodicFunction, W_lin, 0.01*np.ones(len(W_lin)))), name="Lm", line_shape='spline',
#         line=dict(color='rgba(0, 0, 0, 0.3)', width = 2)
#         )
#     )

# fig.add_trace(
#     go.Scatter(
#         x=W_lin, y=list(map(DerevativeFunction, W_lin, 1*np.ones(len(W_lin)))), name="Lm", line_shape='spline',
#         line=dict(color='rgba(0, 0, 0, 0.3)', width = 2)
#         )
#     )

# fig.add_trace(
#     go.Scatter(
#         x=W_lin, y=-90*np.ones(len(W_lin)) 
#                     +list(map(AperiodicFunction, W_lin, 0.2*np.ones(len(W_lin)))) 
#                     +list(map(AperiodicFunction, W_lin, 0.02*np.ones(len(W_lin)))),
#         # mode='lines+markers',
#         line=dict(color='gray')
#         )
#     )

fig.add_trace(
    go.Scatter(
        x=W_lg, y=argWS, name="Lm", line_shape='spline',
        # mode='lines+markers',
        line=dict(color='black')
        )
    )

fig.update_layout(
    # title='ЛАЧХ',  
    autosize=False,
    width=500, height=500,
    margin=dict(l=50, r=50, b=50, t=50),
    template='simple_white',
    xaxis_title=r'lg(ω)',
    yaxis_title=r'Deg'
    )

fig.update_yaxes(tick0=0, dtick=90)

fig.update_xaxes(zeroline=True)
fig.update_yaxes(zeroline=True)

fig.update_xaxes(showgrid=True)
fig.update_yaxes(showgrid=True)

fig.update_yaxes(range=[-270-45, 0+45])
fig.update_xaxes(range=[-3, 4.5])

fig.add_annotation(
    x=4.5, y=-270-45,
    text="",
    ax=-150, ay=0,
    xshift=2,
    yshift=0,
    showarrow=True,
    arrowsize=20,
    arrowwidth=0.1,
    arrowhead=1
    )

fig.add_annotation(
    x=-3, y=0+45,
    text="",
    ax=0, ay=150,
    xshift=0,
    yshift=2,
    showarrow=True,
    arrowsize=20,
    arrowwidth=0.1,
    arrowhead=1
    )
fig.update_layout(showlegend=False)
fig.show()
plotly.io.write_image(fig, 'Численный ЛФЧХ замкнутой системы.pdf', format='pdf')

-164.05460409907712
